// https://github.com/simple-icons/simple-icons/blob/master/slugs.md
exports.langSlugs = [
  { slug: "html5" },
  { slug: "css3" },
  { slug: "javascript" },
  { slug: "c" },
  { slug: "cplusplus" },
  { slug: "nodedotjs" },
  { slug: "java" },
  { slug: "latex" },
  { slug: "markdown" },
  { slug: "gnubash" },
  { slug: "json" },
  { slug: "svg" },
  { slug: "sass" },
  { slug: "php" },
];

exports.libSlugs = [
  { slug: "githubactions" },
  { slug: "tailwindcss" },
  { slug: "vuedotjs" },
  { slug: "arduino" },
  { slug: "threedotjs" },
  { slug: "wordpress" },
  { slug: "bootstrap" },
  { slug: "express" },
  { slug: "chartdotjs" },
  { slug: "materialdesign" },
  { slug: "nuxtdotjs" },
  { slug: "vuetify" },
];

exports.hostSlugs = [
  { slug: "firebase" },
  { slug: "githubpages" },
  { slug: "netlify" },
  { slug: "vercel" },
  { slug: "heroku" },
  { slug: "postgresql" },
  { slug: "mysql" },
  { slug: "mongodb" },
];

exports.toolSlugs = [
  { slug: "docker" },
  { slug: "git" },
  { slug: "npm" },
  { slug: "prettier" },
  { slug: "puppet" },
  { slug: "webpack" },
  { slug: "vite" },
  { slug: "babel" },
  { slug: "visualstudiocode" },
  { slug: "postman" },
  { slug: "postcss" },
  { slug: "popos" },
  { slug: "gimp" },
  { slug: "linux" },
  { slug: "anydesk" },
  { slug: "apachetomcat" },
  { slug: "ubuntu" },
  { slug: "redhat" },
  { slug: "bitbucket" },
  { slug: "jira" },
  { slug: "canva" },
  { slug: "cpanel" },
  { slug: "duckduckgo" },
  { slug: "eslint" },
  { slug: "godaddy" },
  { slug: "googleanalytics" },
  { slug: "jenkins" },
  { slug: "phpmyadmin" },
  { slug: "purgecss" },
  { slug: "pwa" },
  { slug: "salesforce" },
  { slug: "serverless" },
  { slug: "torproject" },
  { slug: "vmware" },
  { slug: "xampp" },
];

exports.socialSlugs = [
  { slug: "github", url: "https://github.com/venkivijay" },
  { slug: "linkedin", url: "https://linkedin.com/in/venkivijay" },
  { slug: "twitter", url: "https://twitter.com/venkivijay_" },
  {
    slug: "googlechrome",
    url: "https://venkivijay.com",
    text: "venkivijay.com",
  },
  {
    slug: "googlechrome",
    url: "https://links.venkivijay.com",
    text: "Other socials",
  },
];
